name: 'Release Notes Generator'
description: 'Generates release notes using semantic-release/release-notes-generator'
author: 'Fredrik Arvidsson'
inputs:
  github_token:
    description: 'The Github token used to query this repository'
    required: true
    default: ${{ github.token }}
  version:
    description: 'The version of the release'
    required: true
  from_ref_exclusive:
    description: >-
      The commit reference to gather commits after. 
      The reference can be a tag, a branch or a commit sha.
      Examples:
        tags/v1.0.1
        v1.0.1
        heads/my-branch
        my-branch
        431880b
    required: true
  to_ref_inclusive:
    description: >-
      The last commit reference to include. 
      The reference can be a tag, a branch or a commit sha.
      Examples:
        tags/v2.0.0
        v2.0.0
        heads/master
        master
        531c800
    required: true
outputs:
  release_notes:
    description: 'Semantic release notes'
runs:
  using: 'composite'
  steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
      shell: bash
    - name: Dump env context
      env:
        ENV_CONTEXT: ${{ toJSON(env) }}
      run: echo "$ENV_CONTEXT"
      shell: bash
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
      shell: bash
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"
      shell: bash
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: echo "$RUNNER_CONTEXT"
      shell: bash
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
      shell: bash
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"
      shell: bash
    # - run: |
    #     echo "${{ toJSON(github) }}"
    #     echo "${{ toJSON(env) }}"
    #     echo "${{ toJSON(job) }}"
    #     echo "${{ toJSON(steps) }}"
    #     echo "${{ toJSON(runner) }}"
    #     echo "${{ toJSON(strategy) }}"
    #     echo "${{ toJSON(matrix) }}"
    #     echo "${{ toJSON(needs) }}"
    #   shell: bash
    # - run: curl -L "${github.server_url}/${github.action_repository}/archive/"
    # shell: bash
# runs:
#   using: 'node12'
#   main: 'lib/main.js'
branding:
  icon: 'file-text'
  color: 'orange'
