name: 'Release Notes Generator'
description: 'Generates release notes using semantic-release/release-notes-generator'
author: 'Fredrik Arvidsson'
inputs:
  github_token:
    description: 'The Github token used to query this repository, usually ${{ secrets.GITHUB_TOKEN }}'
    required: true
  version:
    description: 'The version of the release'
    required: true
  from_ref_exclusive:
    description: >-
      A reference where to start gather commits. 
      The reference can be a tag, a branch or a commit sha.
      The reference is not included.
      Examples:
        tags/v1.0.1
        heads/my-branch
        431880b
    required: true
  to_ref_inclusive:
    description: >-
      The reference where to stop gather commits. 
      The reference can be a tag, a branch or a commit sha.
      The reference is included.
      Examples:
        tags/v2.0.0
        heads/master
        531c800
    required: true
outputs:
  release_notes:
    description: 'Semantic release notes'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'file-text'
  color: 'orange'
