name: 'Semantic Release Notes Generator'
description: 'Generates release notes using semantic-release/release-notes-generator'
author: 'Fredrik Arvidsson'
inputs:
  version:
    description: 'The version of the release'
    required: true
  last_release_ref:
    description: >-
      The commit reference of the last release. 
      The reference can be a tag, a branch or a commit sha.
      Examples:
        tags/v1.0.1
        v1.0.1
        heads/my-branch
        my-branch
        431880b
    required: true
  release_ref:
    description: >-
      The commit reference of this release. 
      The reference can be a tag, a branch or a commit sha.
      Examples:
        tags/v2.0.0
        v2.0.0
        heads/master
        master
        531c800
    required: true
  path_to_commits:
    description: >-
      The path to a file containing the commit messages and shas to parse as release notes.
      Example:
        ./commit-logs.json

      The content of the file should be formatted as a JSON list of commit message objects, example:
        [{"hash": "62c0a92ed8c684f966391c97ef68fcd7560ff666", "message": "This is a commit message"}]
    required: true
  github_token:
    description: 'Authorized GitHub Access Token used to fetch the release notes generator. Defaults to github.token'
    required: false
    default: ${{ github.token }}
outputs:
  release_notes:
    description: 'Semantic release notes'
runs:
  using: 'node20'
  pre: 'fetch_artifact.js'
  main: 'dist/index.js'
branding:
  icon: 'file-text'
  color: 'orange'
