name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
        with:
          # Fetches entire history, so we can analyze commits since last tag
          fetch-depth: 0
      - name: Install
        run: npm ci
      - name: Check
        run: npm run prettier-check
      - name: Build
        run: npm run build
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          configFilePath: .github/version_config.yml
      - name: Determine Version Output
        id: versions
        run: |
          version=v${{ steps.gitversion.outputs.semVer }}
          from_ref_exclusive=${{ steps.gitversion.outputs.versionSourceSha }}
          [[ "${{ github.ref }}" ==  "refs/heads/main" ]] && \
            to_ref_inclusive=$version || \
            to_ref_inclusive=${{ steps.gitversion.outputs.sha }}

          echo "::set-output name=version=$version"
          echo "::set-output name=from_ref_exclusive=$from_ref_exclusive"
          echo "::set-output name=to_ref_inclusive=$to_ref_inclusive"
      - name: Create tag
        if: github.ref == 'refs/heads/main'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.versions.outputs.version }}",
              sha: context.sha
            })
      - name: Generate Release Notes
        id: release_notes
        uses: ./
        with:
          version: ${{ steps.versions.outputs.version }}
          from_ref_exclusive: ${{ steps.versions.outputs.from_ref_exclusive }}
          to_ref_inclusive: ${{ steps.versions.outputs.to_ref_inclusive }}
