name: Preview Release Notes

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
        with:
          # Fetches entire history, so we can analyze commits since last tag
          fetch-depth: 0
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          configFilePath: .github/version_config.yml
      - name: Determine Release Info
        id: release
        run: |
          tag=v${{ steps.gitversion.outputs.semVer }}
          from_tag=$(git tag --contains ${{ steps.gitversion.outputs.versionSourceSha }} | grep -m 1 ^v[0-9]*\.[0-9]*\.g[0-9]* | head -1)
          [[ -z "$from_tag" ]] && \
            from_ref_exclusive=${{ steps.gitversion.outputs.versionSourceSha }} || \
            from_ref_exclusive=$from_tag

          echo "::set-output name=tag::$tag"
          echo "::set-output name=from_ref_exclusive::$from_ref_exclusive"
      - name: Generate Release Notes
        id: release_notes
        uses: ./
        with:
          version: ${{ steps.release.outputs.tag }}
          from_ref_exclusive: ${{ steps.release.outputs.from_ref_exclusive }}
          to_ref_inclusive: ${{ steps.gitversion.outputs.sha }}
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ```
            ${{ steps.release_notes.outputs.release_notes }}
            ```
